### PR TITLE
Upgrade packages to make it work with stack

### PR DESCRIPTION
**Pull request by sergey-kintsel**

### CODE REVIEW

**Comment by sergey-kintsel** [comment]
@danstiner could you take a look? also, I'd appreciate if you help me with the failures on CI

**Comment by danstiner** [comment]
Thanks for looking at this! I believe by dropping GHC 7 support and making some small tweaks to your changes in another PR everything is working. I don't have time to wait for all the builds to finish and confirm that today, but I'll try to finish this out in the next couple days.

**Comment by danstiner** [comment]
Thanks for your contribution!

**Comment by ahstro** [comment]
Don't mean to be a bother, but I'm also super eager to use this. Would you mind creating a new release now that this has been merged? :innocent:

**Pull request merged**
